### ISSUE TITLE
fist issue! Error in sample.int

### ISSUE THREAD

**Issue by RichardCorbett** [mathieu-lemire/celluloid_0.11_tutorial#1]
Hi there,
I thought I'd give your code a try after seeing the paper.

Command:
`R-3.3.0/bin/Rscript pipeline.r ../../HMMCopy/tum_reads.wig ../../HMMCopy/norm_reads.wig ../../HMMCopy/gc.wig ../../HMMCopy/GRCh37-lite_125bp.map.bw.wig ../hetCounts.txt colo829
`
and after the packes are all loaded I get an error:
`Loading required package: XML
Identifying and ignoring outlier read counts...Error in sample.int(length(x), size, replace, prob) : 
  invalid first argument
Calls: gcCorrect -> gcCorrect.normal -> sample -> sample.int
`

Here are the first lines of each of my wig files:
tum_reads.wig
> fixedStep chrom=1 start=1 step=1000 span=1000
> 0
> 0

norm_reads.wig
> fixedStep chrom=1 start=1 step=1000 span=1000
> 0
> 0

gc.wig
> fixedStep chrom=1 start=1 step=1000 span=1000
> -1
> -1

GRCh37-lite_125bp.map.bw.wig
> fixedStep chrom=1 start=1 step=1000 span=1000
> 0
> 0

hetCounts.txt
> CHR POS REF_COUNT VAR_COUNT
> 10 60637 73 46
> 10 60684 73 43

The files listed above that have lines with 0s and -1s do have proper values once you get in to the meat of the file.  Do you have any ideas of things to check?

**Comment by mathieu-lemire** [comment]
It might be because the code is expecting to find the string "chr" in the chromosome numbers. 

Could you try to see if the following temporary fix would solve the problem?  For each wig file, run this command, and then try my code again with the new files:

sed 's/chrom=/chrom=chr/'  tum_reads.wig > tum_reads_chrstring_wig

etc

Thanks,
Mathieu

**Comment by RichardCorbett** [comment]
High Five.
Looks like its running now.   I changed the wigs as you suggested, and changed each line in the variant call list
`sed 's/^/chr/' ../hetCounts.txt > hetCounts_chrstring.txt`

I'll report back tomorrow about if I got any results out the other end.

**Comment by RichardCorbett** [comment]
Ran to completion. thanks!
